[package]
name = "rust-structures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.90", features = ["derive", "rc"] }
serde_json = "1.0"
time-test = "0.2.3"
